// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package validation



@SerialVersionUID(0L)
final case class ClassCreation(
    _class: String = "",
    args: String = ""
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[ClassCreation] with com.trueaccord.lenses.Updatable[ClassCreation] {
    @transient
    private[this] var __serializedSizeCachedValue: Int = 0
    private[this] def __computeSerializedValue(): Int = {
      var __size = 0
      if (_class != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, _class) }
      if (args != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, args) }
      __size
    }
    final override def serializedSize: Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): Unit = {
      {
        val __v = _class
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = args
        if (__v != "") {
          _output__.writeString(2, __v)
        }
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): validation.ClassCreation = {
      var ___class = this._class
      var __args = this.args
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            ___class = _input__.readString()
          case 18 =>
            __args = _input__.readString()
          case tag => _input__.skipField(tag)
        }
      }
      validation.ClassCreation(
          _class = ___class,
          args = __args
      )
    }
    def with_Class(__v: String): ClassCreation = copy(_class = __v)
    def withArgs(__v: String): ClassCreation = copy(args = __v)
    def getFieldByNumber(__fieldNumber: Int): scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = _class
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = args
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(_class)
        case 2 => _root_.scalapb.descriptors.PString(args)
      }
    }
    override def toString: String = _root_.com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
    def companion = validation.ClassCreation
}

object ClassCreation extends com.trueaccord.scalapb.GeneratedMessageCompanion[validation.ClassCreation] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[validation.ClassCreation] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): validation.ClassCreation = {
    require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    validation.ClassCreation(
      __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(1), "").asInstanceOf[String]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[validation.ClassCreation] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      validation.ClassCreation(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ValidationProto.javaDescriptor.getMessageTypes.get(6)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ValidationProto.scalaDescriptor.messages(6)
  def messageCompanionForFieldNumber(__number: Int): _root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: Int): _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = validation.ClassCreation(
  )
  implicit class ClassCreationLens[UpperPB](_l: _root_.com.trueaccord.lenses.Lens[UpperPB, validation.ClassCreation]) extends _root_.com.trueaccord.lenses.ObjectLens[UpperPB, validation.ClassCreation](_l) {
    def _class: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_._class)((c_, f_) => c_.copy(_class = f_))
    def args: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.args)((c_, f_) => c_.copy(args = f_))
  }
  final val CLASS_FIELD_NUMBER = 1
  final val ARGS_FIELD_NUMBER = 2
}
