// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package validation



@SerialVersionUID(0L)
final case class MethodSign(
    name: String = "",
    className: String = "",
    returnType: String = "",
    paramLst: String = "",
    id: Int = 0
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[MethodSign] with com.trueaccord.lenses.Updatable[MethodSign] {
    @transient
    private[this] var __serializedSizeCachedValue: Int = 0
    private[this] def __computeSerializedValue(): Int = {
      var __size = 0
      if (name != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, name) }
      if (className != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, className) }
      if (returnType != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, returnType) }
      if (paramLst != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, paramLst) }
      if (id != 0) { __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(5, id) }
      __size
    }
    final override def serializedSize: Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): Unit = {
      {
        val __v = name
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = className
        if (__v != "") {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = returnType
        if (__v != "") {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = paramLst
        if (__v != "") {
          _output__.writeString(4, __v)
        }
      };
      {
        val __v = id
        if (__v != 0) {
          _output__.writeInt32(5, __v)
        }
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): validation.MethodSign = {
      var __name = this.name
      var __className = this.className
      var __returnType = this.returnType
      var __paramLst = this.paramLst
      var __id = this.id
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __name = _input__.readString()
          case 18 =>
            __className = _input__.readString()
          case 26 =>
            __returnType = _input__.readString()
          case 34 =>
            __paramLst = _input__.readString()
          case 40 =>
            __id = _input__.readInt32()
          case tag => _input__.skipField(tag)
        }
      }
      validation.MethodSign(
          name = __name,
          className = __className,
          returnType = __returnType,
          paramLst = __paramLst,
          id = __id
      )
    }
    def withName(__v: String): MethodSign = copy(name = __v)
    def withClassName(__v: String): MethodSign = copy(className = __v)
    def withReturnType(__v: String): MethodSign = copy(returnType = __v)
    def withParamLst(__v: String): MethodSign = copy(paramLst = __v)
    def withId(__v: Int): MethodSign = copy(id = __v)
    def getFieldByNumber(__fieldNumber: Int): scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = name
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = className
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = returnType
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = paramLst
          if (__t != "") __t else null
        }
        case 5 => {
          val __t = id
          if (__t != 0) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(name)
        case 2 => _root_.scalapb.descriptors.PString(className)
        case 3 => _root_.scalapb.descriptors.PString(returnType)
        case 4 => _root_.scalapb.descriptors.PString(paramLst)
        case 5 => _root_.scalapb.descriptors.PInt(id)
      }
    }
    override def toString: String = _root_.com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
    def companion = validation.MethodSign
}

object MethodSign extends com.trueaccord.scalapb.GeneratedMessageCompanion[validation.MethodSign] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[validation.MethodSign] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): validation.MethodSign = {
    require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    validation.MethodSign(
      __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(1), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(2), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(3), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(4), 0).asInstanceOf[Int]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[validation.MethodSign] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      validation.MethodSign(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[Int]).getOrElse(0)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ValidationProto.javaDescriptor.getMessageTypes.get(2)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ValidationProto.scalaDescriptor.messages(2)
  def messageCompanionForFieldNumber(__number: Int): _root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: Int): _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = validation.MethodSign(
  )
  implicit class MethodSignLens[UpperPB](_l: _root_.com.trueaccord.lenses.Lens[UpperPB, validation.MethodSign]) extends _root_.com.trueaccord.lenses.ObjectLens[UpperPB, validation.MethodSign](_l) {
    def name: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.name)((c_, f_) => c_.copy(name = f_))
    def className: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.className)((c_, f_) => c_.copy(className = f_))
    def returnType: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.returnType)((c_, f_) => c_.copy(returnType = f_))
    def paramLst: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.paramLst)((c_, f_) => c_.copy(paramLst = f_))
    def id: _root_.com.trueaccord.lenses.Lens[UpperPB, Int] = field(_.id)((c_, f_) => c_.copy(id = f_))
  }
  final val NAME_FIELD_NUMBER = 1
  final val CLASSNAME_FIELD_NUMBER = 2
  final val RETURNTYPE_FIELD_NUMBER = 3
  final val PARAMLST_FIELD_NUMBER = 4
  final val ID_FIELD_NUMBER = 5
}
