// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package validation



object ValidationProto extends _root_.com.trueaccord.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.com.trueaccord.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_]] = Seq(
    validation.Node,
    validation.Extend,
    validation.MethodSign,
    validation.ConstrSign,
    validation.ThisInvocation,
    validation.MethodInvocation,
    validation.ClassCreation,
    validation.UseRetStmt,
    validation.RetStmt,
    validation.VariableInitialization,
    validation.SuperInvocation,
    validation.Type,
    validation.TypeResponse,
    validation.Response
  )
  private lazy val ProtoBytes: Array[Byte] =
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChB2YWxpZGF0aW9uLnByb3RvImUKBE5vZGUSIAoLZGVzY3JpcHRpb24YASABKAlSC2Rlc2NyaXB0aW9uEg4KAmlkGAIgASgFU
  gJpZBIVCgZwYXJfaWQYAyABKAVSBXBhcklkEhQKBWRlcHRoGAQgASgFUgVkZXB0aCJCCgZFeHRlbmQSGgoIdHlwZU5hbWUYASABK
  AlSCHR5cGVOYW1lEhwKCXN1cGVyTmFtZRgCIAEoCVIJc3VwZXJOYW1lIooBCgpNZXRob2RTaWduEhIKBG5hbWUYASABKAlSBG5hb
  WUSHAoJY2xhc3NOYW1lGAIgASgJUgljbGFzc05hbWUSHgoKcmV0dXJuVHlwZRgDIAEoCVIKcmV0dXJuVHlwZRIaCghwYXJhbUxzd
  BgEIAEoCVIIcGFyYW1Mc3QSDgoCaWQYBSABKAVSAmlkIkgKCkNvbnN0clNpZ24SEgoEbmFtZRgBIAEoCVIEbmFtZRIOCgJpZBgCI
  AEoBVICaWQSFgoGcGFyYW1zGAMgASgJUgZwYXJhbXMiUgoOVGhpc0ludm9jYXRpb24SGgoIcGFyYW1Mc3QYASABKAlSCHBhcmFtT
  HN0Eg4KAmlkGAIgASgFUgJpZBIUCgVkZXB0aBgDIAEoBVIFZGVwdGgiUAoQTWV0aG9kSW52b2NhdGlvbhISCgRuYW1lGAEgASgJU
  gRuYW1lEhQKBWNsYXNzGAIgASgJUgVjbGFzcxISCgRhcmdzGAMgASgJUgRhcmdzIjkKDUNsYXNzQ3JlYXRpb24SFAoFY2xhc3MYA
  SABKAlSBWNsYXNzEhIKBGFyZ3MYAiABKAlSBGFyZ3MiTAoKVXNlUmV0U3RtdBIYCgdyZXRUeXBlGAEgASgJUgdyZXRUeXBlEg4KA
  mlkGAIgASgFUgJpZBIUCgVkZXB0aBgDIAEoBVIFZGVwdGgiKQoHUmV0U3RtdBIeCgptZXRob2ROYW1lGAEgASgJUgptZXRob2ROY
  W1lIlwKFlZhcmlhYmxlSW5pdGlhbGl6YXRpb24SIgoMZXhwZWN0ZWRUeXBlGAEgASgJUgxleHBlY3RlZFR5cGUSHgoKYWN0dWFsV
  HlwZRgCIAEoCVIKYWN0dWFsVHlwZSJZCg9TdXBlckludm9jYXRpb24SGgoIcGFyYW1Mc3QYASABKAlSCHBhcmFtTHN0EhQKBXBhc
  klkGAIgASgFUgVwYXJJZBIUCgVkZXB0aBgDIAEoBVIFZGVwdGgiKgoEVHlwZRISCgR0eXBlGAEgASgJUgR0eXBlEg4KAmlkGAIgA
  SgFUgJpZCIiCgxUeXBlUmVzcG9uc2USEgoEdHlwZRgBIAEoCVIEdHlwZSIgCghSZXNwb25zZRIUCgV2YWx1ZRgBIAEoCFIFdmFsd
  WUylQUKEFByb2xvZ1ZhbGlkYXRpb24SIQoLYWRkRmFjdE5vZGUSBS5Ob2RlGgkuUmVzcG9uc2UiABIpChF2YWxpZGF0ZUV4dGVuc
  2lvbhIHLkV4dGVuZBoJLlJlc3BvbnNlIgASLgoSdmFsaWRhdGVNZXRob2RTaWduEgsuTWV0aG9kU2lnbhoJLlJlc3BvbnNlIgASM
  woXdmFsaWRhdGVDb25zdHJ1Y3RvclNpZ24SCy5Db25zdHJTaWduGgkuUmVzcG9uc2UiABI2ChZ2YWxpZGF0ZVRoaXNJbnZvY2F0a
  W9uEg8uVGhpc0ludm9jYXRpb24aCS5SZXNwb25zZSIAEi4KEnZhbGlkYXRlVXNlUmV0U3RtdBILLlVzZVJldFN0bXQaCS5SZXNwb
  25zZSIAEigKD3ZhbGlkYXRlUmV0U3RtdBIILlJldFN0bXQaCS5SZXNwb25zZSIAEjgKF3ZhbGlkYXRlU3VwZXJJbnZvY2F0aW9uE
  hAuU3VwZXJJbnZvY2F0aW9uGgkuUmVzcG9uc2UiABI6Chh2YWxpZGF0ZU1ldGhvZEludm9jYXRpb24SES5NZXRob2RJbnZvY2F0a
  W9uGgkuUmVzcG9uc2UiABI8Ch12YWxpZGF0ZUNsYXNzSW5zdGFuY2VDcmVhdGlvbhIOLkNsYXNzQ3JlYXRpb24aCS5SZXNwb25zZ
  SIAEkYKHnZhbGlkYXRlVmFyaWFibGVJbml0aWFsaXphdGlvbhIXLlZhcmlhYmxlSW5pdGlhbGl6YXRpb24aCS5SZXNwb25zZSIAE
  h0KB2FkZFR5cGUSBS5UeXBlGgkuUmVzcG9uc2UiABIhCgdnZXRUeXBlEgUuVHlwZRoNLlR5cGVSZXNwb25zZSIAYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}