// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package validation



@SerialVersionUID(0L)
final case class VariableInitialization(
    expectedType: String = "",
    actualType: String = ""
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[VariableInitialization] with com.trueaccord.lenses.Updatable[VariableInitialization] {
    @transient
    private[this] var __serializedSizeCachedValue: Int = 0
    private[this] def __computeSerializedValue(): Int = {
      var __size = 0
      if (expectedType != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, expectedType) }
      if (actualType != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, actualType) }
      __size
    }
    final override def serializedSize: Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): Unit = {
      {
        val __v = expectedType
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = actualType
        if (__v != "") {
          _output__.writeString(2, __v)
        }
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): validation.VariableInitialization = {
      var __expectedType = this.expectedType
      var __actualType = this.actualType
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __expectedType = _input__.readString()
          case 18 =>
            __actualType = _input__.readString()
          case tag => _input__.skipField(tag)
        }
      }
      validation.VariableInitialization(
          expectedType = __expectedType,
          actualType = __actualType
      )
    }
    def withExpectedType(__v: String): VariableInitialization = copy(expectedType = __v)
    def withActualType(__v: String): VariableInitialization = copy(actualType = __v)
    def getFieldByNumber(__fieldNumber: Int): scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = expectedType
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = actualType
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(expectedType)
        case 2 => _root_.scalapb.descriptors.PString(actualType)
      }
    }
    override def toString: String = _root_.com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
    def companion = validation.VariableInitialization
}

object VariableInitialization extends com.trueaccord.scalapb.GeneratedMessageCompanion[validation.VariableInitialization] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[validation.VariableInitialization] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): validation.VariableInitialization = {
    require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    validation.VariableInitialization(
      __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(1), "").asInstanceOf[String]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[validation.VariableInitialization] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      validation.VariableInitialization(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ValidationProto.javaDescriptor.getMessageTypes.get(9)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ValidationProto.scalaDescriptor.messages(9)
  def messageCompanionForFieldNumber(__number: Int): _root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: Int): _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = validation.VariableInitialization(
  )
  implicit class VariableInitializationLens[UpperPB](_l: _root_.com.trueaccord.lenses.Lens[UpperPB, validation.VariableInitialization]) extends _root_.com.trueaccord.lenses.ObjectLens[UpperPB, validation.VariableInitialization](_l) {
    def expectedType: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.expectedType)((c_, f_) => c_.copy(expectedType = f_))
    def actualType: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.actualType)((c_, f_) => c_.copy(actualType = f_))
  }
  final val EXPECTEDTYPE_FIELD_NUMBER = 1
  final val ACTUALTYPE_FIELD_NUMBER = 2
}
